### PR TITLE
chore: Ignore JetBrains IDEA configuration

### PR DESCRIPTION
**Pull request by l0b0**
Also sort the entries and mark `node_modules` as a directory.

### CODE REVIEW

**Comment by m-mohr** [comment]
I guess we can enable this for more popular IDEs and not just for a single one. Wasn't there somewhere (on GitHub?) a default .gitignore file that had all these included?

**Comment by l0b0** [comment]
What's the next action? Should I just close this, replace the .gitignore with another one, or something else?

**Comment by m-mohr** [comment]
Hmm, when researching what good defaults would be (e.g. add folder for vscode, netbeans, eclipse) I found this:
https://blog.martinhujer.cz/dont-put-idea-vscode-directories-to-projects-gitignore/
This implies we should not merge this but instead leave this up to the devs, which seems to be in line with what GitHub itself does. I tried to generate some default gitignores, but usually no IDEs are included, just the programming language specific folders, e.g. for Node: https://github.com/m-mohr/test/blob/main/.gitignore

**Comment by l0b0** [comment]
I'm more with [this person](http://disq.us/p/2jewgqv). Plenty of the GitHub .gitignore templates also [explicitly list IDEA files](https://github.com/github/gitignore/search?q=.idea).

**Comment by m-mohr** [comment]
Hmm, for me your link points to the link I've posted before, so I'm a bit confused.

**Comment by l0b0** [comment]
> Hmm, for me your link points to the link I've posted before, so I'm a bit confused.

Oh, weird. The first link was directly to one of the comments on that blog post, by "2:22". Unfortunately the browser doesn't scroll to it.

**Comment by l0b0** [comment]
Would you be OK to merge this as-is, then others can add what they want to ignore? Or do you prefer closing this and someone adding a more "standard" .gitignore with lots of stuff in one go?

**Pull request closed without merging**
